### ISSUE TITLE
error building

### ISSUE THREAD

**Issue by B-Nerd** [testyourmine/sm_rewrite#4]
### Describe your bug here. And how to reproduce it. (If possible, please send the save that the bug occurs.)

when i ran the make command after i got this error
src/sm_80.c:1902:3: error: lvalue required as increment operand
 1902 |   ++(uint8)timer_x_pos;
      |   ^~
src/sm_80.c: In function ‘ProcessTimer_MovementDelayed’:
src/sm_80.c:1913:3: error: lvalue required as increment operand
 1913 |   ++(uint8)timer_x_pos;
      |   ^~
make: *** [Makefile:25: src/sm_80.o] Error 1
make: *** Waiting for unfinished jobs....
the fix is change src/sm_80.c line 1902 & 1913 ++(uint8)timer_x_pos; need to be changed to (uint8)++timer_x_pos; or ++timer_x_pos; 
### What is your build target?

Linux

**Comment by testyourmine** [comment]
Bug should be fixed with the latest commit
