### ISSUE TITLE
Entering Draygon's boss room causes game to enter endless loop

### ISSUE THREAD

**Issue by SirGouki** [testyourmine/sm_rewrite#5]
### Describe your bug here. And how to reproduce it. (If possible, please send the save that the bug occurs.)

Upon entering Draygon's Boss room, the window title changes to add "BUG FOUND!", the game starts the room transition, stays black screened and the console starts spamming a bunch of addresses showing which values are not equal:

![image](https://github.com/testyourmine/sm_rewrite/assets/11664236/f8f879e6-2e62-43aa-b0ea-9c3651baef79)

Had this happen twice, the first time I was charging a shine spark, the second time I entered normally.  Note: it still takes inputs during this, so I was able to pause the game so that it'd quit spamming the console to take the screen shot

### What is your build target?

Windows

**Comment by testyourmine** [comment]
There should be a bug save generated, so send that and your normal save file (sm.srm) if you can. If the bug save isn't there (I'm not sure if the timer has to count down to zero first to produce a bug save first), then just send the save file. You can either send them here or on discord.

**Comment by SirGouki** [comment]
[saves.zip](https://github.com/testyourmine/sm_rewrite/files/15355839/saves.zip)
Here you go.  I found them after I posted so I wasn't sure if you'd need them.

**Comment by testyourmine** [comment]
Should be fixed now, let me know if you get any more bugs.
