### ISSUE TITLE
Mother Brain Room triggers BUG FOUND hang

### ISSUE THREAD

**Issue by SirGouki** [testyourmine/sm_rewrite#6]
### Entering Mother Brain Room (prior to the fight, the part where the room fills wit magma and you gotta destroy the Zebetites to progress) causes an endless loop.

This is similar to the Draygon one from before, entering the mother brain room triggers an endless loop of this: 

![image](https://github.com/testyourmine/sm_rewrite/assets/11664236/95cc1bec-7057-4b93-8d92-c54e7a606134)

Saves: 
[saves.zip](https://github.com/testyourmine/sm_rewrite/files/15368653/saves.zip)

No save state this time as the last time I dropped one was before Ridley.  

Killing something with the grapple beam seems to trigger a bug found print out too, but those don't hang and I didn't notice right away that it was happening, but those don't lock the game up, and the game seems to progress fine regardless.  If you need to see them, I can trigger it again next time I play.

### What is your build target?

Windows

**Comment by testyourmine** [comment]
Fixed these, seems like I made mistakes when I did the first round of data extraction.
